import type { Metadata } from "next";
import "./globals.css";
import './hamburguer.css'

import Header from "./components/Header";

import { balsamiqSans } from './assets/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={`${balsamiqSans.className} bg-bg-body text-white pb-[80px]`}>
        <Header />
        <div className='w-[95%] max-w-[1440px] m-auto  mt-[100px] min-h-[95vh]'>
          {children}
        </div>
      </body>
    </html>
  );
}
